after-login-command = []
after-startup-command = []

start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']


[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 8
inner.vertical = 8
outer.left = 0
outer.bottom = 0
outer.top = 0
outer.right = 0

[mode.main.binding]
cmd-h = []                                       # Disable "hide application"
cmd-alt-h = []                                   # Disable "hide others"
alt-shift-r = 'layout tiles horizontal vertical'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-semicolon = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

alt-1 = 'workspace 1' # Coding editor
alt-2 = 'workspace 2' # Terminal
alt-3 = 'workspace 3' # Browser
alt-4 = 'workspace 4' # Messaging
alt-5 = 'workspace 5' # Spotify
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-q = 'workspace Q'
alt-w = 'workspace W' # AI 
alt-d = 'workspace D' # Other work related apps
alt-v = 'workspace V' # Linear etc.

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-d = 'move-node-to-workspace D'
alt-shift-q = 'move-node-to-workspace Q'
alt-shift-w = 'move-node-to-workspace W'
alt-shift-v = 'move-node-to-workspace V'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-node-to-monitor --wrap-around next'

alt-shift-semicolon = 'mode service'

alt-shift-m = 'fullscreen'
alt-shift-e = 'balance-sizes'
alt-shift-f = 'layout floating tiling'

[mode.service.binding]
esc = ['reload-config', 'mode main']
# reset layout
r = ['flatten-workspace-tree', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

[[on-window-detected]]
if.app-id = 'com.1password.1password'
check-further-callbacks = true
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.ActivityMonitor'
check-further-callbacks = true
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.calculator'
check-further-callbacks = true
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.Home'
check-further-callbacks = true
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.cron.electron'
check-further-callbacks = true
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
check-further-callbacks = true
run = ['move-node-to-workspace 3']

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
check-further-callbacks = true
run = ['move-node-to-workspace 4']

# Google Chat PWA
[[on-window-detected]]
if.app-id = 'com.google.Chrome.app.mdpkiolbdkhdjpekfbkbmhigcaggjagi'
check-further-callbacks = true
run = ['move-node-to-workspace 4']

[[on-window-detected]]
if.app-id = 'com.spotify.client'
check-further-callbacks = true
run = ['move-node-to-workspace 5']

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
check-further-callbacks = true
run = ['move-node-to-workspace D']

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
check-further-callbacks = true
run = ['move-node-to-workspace 1']

# Code OSS PWA
[[on-window-detected]]
if.app-id = 'com.google.Chrome.app.bpoolcepmmobchiibclcagcjhfaafnbj'
check-further-callbacks = true
run = ['move-node-to-workspace 1']

[[on-window-detected]]
if.app-id = 'com.todesktop.230313mzl4w4u92'
check-further-callbacks = true
run = ['move-node-to-workspace 1']

[[on-window-detected]]
if.app-id = "com.mitchellh.ghostty"
check-further-callbacks = true
run = ["move-node-to-workspace 2"]

[[on-window-detected]]
if.app-id = "com.apple.iphonesimulator"
check-further-callbacks = true
run = ["move-node-to-workspace Q"]

[[on-window-detected]]
if.app-id = "com.apple.iphonesimulator"
check-further-callbacks = true
run = ["move-node-to-workspace Q"]

[[on-window-detected]]
if.app-id = "com.linear"
run = "move-node-to-workspace V"

[[on-window-detected]]
if.app-id = "com.linear"
check-further-callbacks = true
run = ["move-node-to-workspace V"]

[[on-window-detected]]
if.app-id = "com.anthropic.claudefordesktop"
check-further-callbacks = true
run = ["move-node-to-workspace W"]
