[buf]
disabled = true

[character]
error_symbol = "[󰘧](bold red)"
success_symbol = "[󰘧](bold green)"

[directory]
truncate_to_repo = false

[git_branch]
symbol = " "
truncation_length = 18

[lua]
symbol = " "

[package]
disabled = true

[gcloud]
disabled = true
