[user]
email = "szymon.ograbek2@gmail.com"
name = "Szymon Ograbek"


[git]
auto-local-bookmark = false

[revsets]
log = '''
  trunk()
  | (trunk()..@)::
  | (trunk().. & ::heads(bookmarks() ~ trunk()))
'''

[[--scope]]
--when.repositories = ["~/dev/Karen"]
[--scope.user]
email = "szymon.ograbek@44pixels.ai"
name = "Szymon Ograbek"

[revset-aliases]
"immutable_heads()" = "builtin_immutable_heads() | bookmarks(exact:'master') | bookmarks(exact:'main')"
"mine()" = "author('szymon.ograbek@44pixels.ai') | author('szymon.ograbek2@gmail.com')"
